### ISSUE TITLE
Where Clause OR issue

### ISSUE THREAD

**Issue by mjbelow** [Christian-Schou/SuperHeroApi#3]
I'm trying to utilize the OR in filtering, and there seems to be a bug

All of the following where clauses produce the same query, which is AND

I can't get it to work for OR

```
query {
  superheroes
  (where: {name: {contains: "b", or: {contains: "l"}}})
  #(where: {name: {contains: "b"}, or: {name: {contains: "l"}}})
  #(where: {name: {contains: "b", and: {contains: "l"}}})
  #(where: {name: {contains: "b"}, and: {name: {contains: "l"}}})
  {
    name
  }
}
```

The query should return Batman, Luke Skywalker, and Black Widow

![firefox_dHrncLiBkS](https://user-images.githubusercontent.com/55146074/223741399-d4dc17f4-b696-4d14-a099-27e89d92bb98.png)

**Comment by mjbelow** [comment]
So I'm wondering if this is either a bug with the library or I'm just running an incorrect query

Because in my current project, I'm using the latest versions of these packages and still get the same issue.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f3b521b2-9586-42b5-9960-f8e247f7710f</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" Version="13.0.4" />
    <PackageReference Include="HotChocolate.Data.EntityFramework" Version="13.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
  </ItemGroup>

</Project>
```

**Comment by Christian-Schou** [comment]
Hi @mjbelow 👋

To use [filtering](https://chillicream.com/docs/hotchocolate/v12/fetching-data/filtering) like `OR` and `AND`, you have to add a filter type on the Superhero. Have you implemented that for the query type? 😊

**Comment by mjbelow** [comment]
Here's the schema I have

[schema.graphql.txt](https://github.com/Christian-Schou/SuperHeroApi/files/10922943/schema.graphql.txt)

**Comment by Christian-Schou** [comment]
Hi @mjbelow 👋

Ok, looks like you have added the `and` + `or` filter on the superhero input based on your schema. Can you please try the following query:

```graphql
query {
  superheroes(
    where: {
      or: [{ name: {contains: "b" } },  { name: { contains: "l" } }]
  {
    name
  }
}
```

Please let me know the output from that query 😊

**Comment by mjbelow** [comment]
Hey @Christian-Schou it looks like that did it, I appreciate your help with this! 🥳 👍 

![firefox_GqSofJ3acV](https://user-images.githubusercontent.com/55146074/224427237-da5e884e-e3b7-43db-be85-5879f79aa16e.png)

```
      SELECT [s].[Name]
      FROM [Superheroes] AS [s]
      WHERE ((@__p_0 LIKE N'') OR (CHARINDEX(@__p_0, [s].[Name]) > 0)) OR ((@__p_1 LIKE N'') OR (CHARINDEX(@__p_1, [s].[Name]) > 0))
```

**Comment by Christian-Schou** [comment]
You are very welcome @mjbelow ✌️ 😀
