### ISSUE TITLE
Null Variables

### ISSUE THREAD

**Issue by mjbelow** [Christian-Schou/SuperHeroApi#4]
Hi @Christian-Schou , I have another question about queries
I'm wanting to expand upon the issue I had before #3 with the same schema [schema.graphql.txt](https://github.com/Tech-With-Christian/SuperHeroApi/files/11273243/schema.graphql.txt)

I'm wanting to define a query and being able to pass in variables to filter by.
And I've been able to implement this no problem with type `[StringOperationFilterInput!]`

![firefox_8NV3HiuMu7](https://user-images.githubusercontent.com/55146074/233081040-043db97b-f2b8-445e-84a2-87083d8c3554.png)

The problem I'm experiencing is sometimes these variables will be null, and this is the result if I define the variable as null or exclude it completely.

![firefox_3I4S2itCjT](https://user-images.githubusercontent.com/55146074/233081033-9b9c61e1-7208-43fd-ad28-4f549e116e9c.png)

I tried to do the same thing using a variable with type `StringOperationFilterInput`

![firefox_HSAbdY2qEJ](https://user-images.githubusercontent.com/55146074/233081041-7426f274-0d75-4fdb-912c-ccdd1c74a652.png)

And if I defined the variable as null or excluded, I get a more understandable error of Null values not being supported

![firefox_4G9ei94Imb](https://user-images.githubusercontent.com/55146074/233081038-e651c4a4-b582-400f-bd44-87e24a52b91a.png)

So are array variables not allowed to be null as well, or is there another way to do it?

**Comment by Christian-Schou** [comment]
Hi @mjbelow 👋

Sorry for the late reply... Got a lot of stuff on my plate at the moment. Have you solved your issue yet? If not, please see below 😊

In GraphQL, arrays can be nullable, meaning they can have a null value. However, the behavior of arrays with HotChocolate can depend on how you've implemented your schema. I just had a look at the schema you provided in the link. In that schema, the `SuperheroFilterInput` object is not allowed to be null. This is because the `where` argument of the `superheroes` field has a ! after `SuperheroFilterInput`.

```yaml
type Query {
  superheroes(
    where: SuperheroFilterInput! # <-- This means SuperheroFilterInput cannot be null
    skip: Int
    take: Int
  ): [Superhero!]!
}

input SuperheroFilterInput {
  id: IDFilterInput
  name: StringOperationFilterInput
  ... # other fields
}
```

This means that when querying the superheroes field, you must provide a non-null SuperheroFilterInput object as the value for the where argument. To allow the `SuperheroFilterInput` object to be nullable in your current `Query` class using HotChocolate, you need to make the `where` parameter nullable by adding a `?` after `SuperheroFilterInput`.

```csharp
namespace SuperHeroApi.Data
{
    public class Query
    {
        [UseProjection]
        [UseFiltering]
        [UseSorting]
        public IQueryable<Superhero> GetSuperheroes(
            [Service] ApplicationDbContext context, 
            SuperheroFilterInput? where) // makes the where parameter nullable
        {
            IQueryable<Superhero> query = context.Superheroes;

            if (where != null) // check if the where parameter is not null
            {
                // add filtering based on the values in the where object
                query = query.Where(x => x.Name.Contains(where.NameContains));
                // add additional filtering for other fields if needed
            }

            return query;
        }
    }
}

```

In the second image you added I can see a syntax error in your 'where' argument of the 'superheroes' field. The 'or' operator is invalid in your 'where' argument. This should work for you:

```graphql
query ($nameFilter: [StringOperationFilterInput!]) {
  superheroes(where: { 
    name: {
      or: $nameFilter
    }
  }) {
    name
  }
}
```

I hope that answers your question. Please let me know how it works out for you 😊

**Comment by mjbelow** [comment]
Hey @Christian-Schou, no problem I've had a lot on my plate as well

For my particular use case, I decided to take a different path from my original plan.

For my where filter, instead of passing in multiple variables within the where clause, I'm passing in the entire where object as a variable, with this object having possible null values.
Then using GraphQLHttpClient configured to ignore null values, which suits my needs better than my original plans.

```
new GraphQLHttpClient(url,
            new NewtonsoftJsonSerializer(new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
            })
            );
```

Though, I still think my original issue might still be a bug.

First off, my where object does allow nulls, but beside that, I was wanting to pass in possible null OR `[StringOperationFilterInput!]` values for StringOperationFilterInput, which in the schema shows that they could be null

```
type Query {
  superheroes(
    where: SuperheroFilterInput
    order: [SuperheroSortInput!]
  ): [Superhero!]!
}

input SuperheroFilterInput {
  and: [SuperheroFilterInput!]
  or: [SuperheroFilterInput!]
  id: ComparableGuidOperationFilterInput
  name: StringOperationFilterInput
  description: StringOperationFilterInput
  height: ComparableDoubleOperationFilterInput
  superpowers: ListFilterInputTypeOfSuperpowerFilterInput
  movies: ListFilterInputTypeOfMovieFilterInput
}

input StringOperationFilterInput {
  and: [StringOperationFilterInput!]
  or: [StringOperationFilterInput!]
  eq: String
  neq: String
  contains: String
  ncontains: String
  in: [String]
  nin: [String]
  startsWith: String
  nstartsWith: String
  endsWith: String
  nendsWith: String
}
```

Like, here's an example using ORDER `[SuperheroSortInput!]`, which is another array that isn't required and behaves as expected when passed in as a null.

![firefox_mX4YUhpu0t](https://user-images.githubusercontent.com/55146074/236689914-90e92ed7-014b-41bc-acc7-fd8dfc4fcc06.png)

![firefox_d04j9C4kSG](https://user-images.githubusercontent.com/55146074/236689920-b0a59909-46eb-4f31-bf70-40da30413ee5.png)

**Comment by Christian-Schou** [comment]
Hi @mjbelow 👋

Not sure what the issue is now. Do you need my help/input on a specific issue? 😊
